### ISSUE TITLE
Working Collaboratively on Pull Requests

### ISSUE THREAD

**Issue by dakebl** [thepracticaldev/1pr#28]
The collaborative effort going into the pull requests, with everyone chipping in and being supportive of one another, is great to see. I think we should nurture that collaborations as much as possible 😄 

With that in mind however, @DominicBisset has raised a fairly good point in the conversation feed of PR https://github.com/thepracticaldev/1pr/pull/23 

> Tangential question:
Is the meta for this to build every feature into one single monolithic Pull Request that can't be ignored? I was pushing for smaller, individual-feature-focused in the comments for PR #13 but was I wrong in this?

I don't think this is a problem with https://github.com/thepracticaldev/1pr/pull/23 as @woubuc has asked everyone for their permission before merging their PR's into his own, but I can see this becoming more of a problem as the project gets busier.

Perhaps it would be good if folks good post their view on this point here?

We could then use the outcome of the discussion to set up a decent CONTRIBUTING.md for the project?

**Comment by dakebl** [comment]
To kick the conversation off:

I'm of the opinion that, as a matter of practice, we should only merge in another pull requests if the target PR is dependent on doing so, or if we create duplicate/similar pull requests and want to collaboratively consolidate our efforts.

That would ensure that smaller pull requests are not the victim of any biased inter-merging, without hindering those who want to collaborate on similar features/ideas.

**Comment by woubuc** [comment]
Yeah, it's really cool to see how we're all building on top of each other's work e.g. in #23, #24 and #27 😄 

I don't think there's an inherent problem with merging multiple PRs together into one big one, so long as the situation warrants it like you said @dakebl.

One thing I'd add to the contributing guidelines would be: reference the merged forks/branches/PRs if you merge other changes into your PR.
For example, #24 continues to build on top of the work of #23 but when looking at #23 it's not really clear that #24 continues from there. If you mention a PR in another PR, the mentioned one gets a notification that it was mentioned so you can more easily "follow the trail".
I think this would also help @benhalpern quite a lot when checking out the PRs and figuring out which one to merge.

**Comment by dakebl** [comment]
Good thinking @woubuc and my bad with the PR trail 😄 
I agree that we should make this as visible and transparent to @benhalpern as possible!

**Comment by DominicBisset** [comment]
#24 builds on #23?  #27 builds on #24? That is not obvious to me as a fairly inexperienced GitHub user.  Even now I've actively looked I'm still not entirely sure where it says this (is it one of the `merge pull request #[prID] from [user that is not thepracticaldev]/master` lines?).

It's also not clear therefore what the full extent of changes involved in a PR is.  #24 suggests that it does the following:

> I moved the H1 padding to a parent div and I moved the 'last merged pr' section into it.
> I re-added the PR Shield from shields .io (Originally introduced by nrobinson2000 ) . I styled it to be more prominent on the page.
> I added Font Awesome and replaced the text in the Nav with Icons. This looks better on mobile.
> The footer needs styling for mobile, so I added a media query to remove the footer on small devices until it can be made mobile friendly.
> Updated dev.to link to point at https://dev.to/t/1pr

Does it really do that plus all the changes in #23, i.e.:

> I added a .editorconfig file and added some guidelines and coding standards to the readme. I've tried to keep it beginner-friendly, and not too restrictive, but of course this is a starting point and I welcome a discussion around which standards we should follow.
> 
> Even with a "freeform" project like this one, I think it wouldn't hurt to have some coding standards in place, because it will make it easier for others to pick up and join in at any point.
> 
> Some other things:
> 
> Cleaned up the code
> Small css tweaks
> Merged in srebalaji's changes (#20)
> Separated XMLHttpRequest code to be a bit more DRY
> Replaced the png image of the PR icon with an svg version
> Merged in nrobinson2000's footer (#22)
> Made the links on the page itself open in a new window
> Merged in grimreaper's license (#14)
> Merged in grimreaper's CI tests (#15)
> Check it out at https://woubuc.github.io/1pr/

If we're building on each other's PRs I think we should note all the changes that are involved in those PRs as well.  E.g. #24 would be:

> I moved the H1 padding to a parent div and I moved the 'last merged pr' section into it.
> I re-added the PR Shield from shields .io (Originally introduced by nrobinson2000 ) . I styled it to be more prominent on the page.
> I added Font Awesome and replaced the text in the Nav with Icons. This looks better on mobile.
> The footer needs styling for mobile, so I added a media query to remove the footer on small devices until it can be made mobile friendly.
> Updated dev.to link to point at https://dev.to/t/1pr
> 
> Full changes:
>  - Re-added the PR Shield
>  - Updated dev.to link
>  - UI tweaks for H1 and footer
>  - Merged in woubuc's changes (#23):
>    - Added a .editorconfig file
>    - Separated XMLHttpRequest code to be a bit more DRY
>    - Replaced the png image of the PR icon with an svg version
>    - Made the links on the page itself open in a new window
>    - Cleaned up the code
>    - Small css tweaks
>    - Merged in srebalaji's changes (#20):
>      - _List srebalaji's changes_
>    - Merged in nrobinson2000's footer (#22)
>    - Merged in grimreaper's license (#14)
>    - Merged in grimreaper's CI tests (#15)

_@-mentions removed to avoid pinging many users but recommended in reality_
To elaborate: I recommend leading with an explanation about what your PR does and why (as people already do), and then list the changes again in summary in a bulleted list. If the source PRs are single atomic features then those features can be included inline like grimreaper's two PRs above.  Otherwise the changes should be a new level of nested bullets. The Full Changes would then become a nested list that gives the complete story of what is included.  It shouldn't be too difficult to maintain this.  If everyone follows the guidelines, people can just copy and paste the Full Changes from their source PRs.

I know this doesn't really answer the question but this got really long.  I'll follow up with my thoughts on the matter later.

**Comment by woubuc** [comment]
I don't think you should write the changes from another PR again in the description, but you should at least say that you've merged in the changes from a PR.
So like your example _"Merged in woubuc's changes (#23)"_ will then create a link to #23 that people can click on to find out what changed, without you having to write / copy all the changes from #23.

That said, if the idea is to merge the changes into another PR (like @dakebl said), I think it would be better to encourage creating PRs on the fork instead of on the main repo, so we don't create too much 'clutter' in here.
And here again - if you mention the main PR, there will be a notification in the mentioned PR discussion that links to the PR on the fork. I did that with nrobinson2000/1pr#2 and you can see in #18 where I mentioned it, this creates a trail so people can easily see what's going on.

The idea of mentioning PRs (especially cross-repo) to create a trail should probably be explained a bit in contributing.md if we add one, for people who aren't that familiar with Github.

**Comment by dakebl** [comment]
Yeah, I think this highlights the need for some easy to follow guidelines, that make sense to all levels of experience. We all want to be able to understand what we are looking at easily and thoroughly, and getting on the same page with our approach will help ensure that.

**Comment by nrobinson2000** [comment]
@dakebl @woubuc https://github.com/thepracticaldev/1pr/pull/27 Now has a longer trail as I have merged #23 and #24 and added the gitter integration.

**Comment by dakebl** [comment]
Can we get your 10 cents @benhalpern ?
